server {
    listen 80;
    
    # 1. Phục vụ file React tĩnh
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Quan trọng: Nếu F5 ở trang con (/login), chuyển về index.html để React Router xử lý
        try_files $uri $uri/ /index.html;
    }

    # 2. (Tùy chọn) Proxy API để tránh CORS và giấu port 8080
    # Nếu dùng cái này thì trong code React sửa baseURL thành '/api' thay vì 'http://localhost:8080/api'
    # location /api {
    #     proxy_pass http://backend:8080;
    # }
}