version: '3.8'

services:
  # 1. Database
  postgres:
    image: postgres:16-alpine
    container_name: eas_postgres
    environment:
      POSTGRES_DB: appstore_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 2. MinIO
  minio:
    image: minio/minio
    container_name: eas_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  # 3. ClamAV
  clamav:
    image: clamav/clamav:latest
    container_name: eas_clamav
    environment:
      CLAMAV_NO_FRESHCLAM: "false"
    networks:
      - app-network

  # 4. BACKEND (Spring Boot)
  backend:
    build: ./backend
    container_name: eas_backend
    ports:
      - "8080:8080"
    environment:
      # Cấu hình DB
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/appstore_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      
      # Cấu hình MinIO (Viết hoa, thay dấu chấm bằng gạch dưới)
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=miniopassword
      - MINIO_BUCKET=app-installers
      
      # Cấu hình ClamAV
      - CLAMAV_HOST=clamav

      - ELASTIC_HOST=elasticsearch


      - APP_BASE_URL=https://upc-performer-physicians-juan.trycloudflare.com

    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
      clamav:
        condition: service_started
      # --- SỬA DÒNG NÀY ---
      elasticsearch:
        condition: service_healthy # Chỉ chạy khi Elastic đã Healthy
      # --------------------
    networks:
      - app-network

  # 5. FRONTEND (React)
  frontend:
    build: ./frontend
    container_name: eas_frontend
    ports:
      - "3000:80" # Map cổng 80 của Nginx ra cổng 3000 của máy thật
    depends_on:
      - backend
    networks:
      - app-network


  # 6. Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    container_name: eas_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  # 9. Keycloak (Identity Server)
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: eas_keycloak
    command: start-dev # Chạy chế độ Dev cho nhanh
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080" # Map ra cổng 8081 để không đụng backend 8080
    networks:
      - app-network

volumes:
  postgres_data:
  minio_data:
  elastic_data:
networks:
  app-network:
    driver: bridge