server:
  port: 8080

spring:
  application:
    name: enterprise-app-store
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/appstore_db
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Enterprise dùng Flyway nên validate là chuẩn
    properties:
      hibernate:
        # fullName (Java) -> full_name (SQL)
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        format_sql: true
    show-sql: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          # Đường dẫn để Backend kiểm tra chữ ký Token (Issuer URI)
          # Lưu ý: Backend chạy trong Docker nên phải gọi keycloak:8080
          issuer-uri: http://keycloak:8080/realms/enterprise-realm
          # Link để lấy Public Key (JWK Set)
          jwk-set-uri: http://keycloak:8080/realms/enterprise-realm/protocol/openid-connect/certs

  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  elasticsearch:
    uris: http://${ELASTIC_HOST:localhost}:9200
    socket-timeout: 10s

# Các cấu hình tùy chỉnh (Custom Properties) nên để ở cấp ngoài cùng 
# để dễ quản lý bằng @ConfigurationProperties
minio:
  url: http://${MINIO_HOST:localhost}:9000
  access-key: minioadmin
  secret-key: miniopassword
  bucket: app-installers

clamav:
  host: ${CLAMAV_HOST:localhost}
  port: 3310

app:
  base-url: https://link-moi-cua-ban.trycloudflare.com